{
   "entities":[
      {
         "bp_name":"CentOS_IaaS",
         "profile_name":"Default",
         "app_name":"CentOS_Workstation",
         "app_description":"End user CentOS Workstation",
         "variables":[
            {
               "name":"password",
               "value":"nutanix/4u"
            }
         ]
      },
      {
         "bp_name":"Wordpress",
         "profile_name":"Small_AHV",
         "app_name":"Wordpress_App",
         "app_description":"To access Wordpress, launch the console of your Windows Workstation, and enter in the IP address of the Ha_Proxy VM into a web browser.",
         "variables":[
            {
               "name":"MYSQL_PASSWORD",
               "value":"nutanix/4u"
            },
            {
               "name":"WP_DB_PASSWORD",
               "value":"nutanix/4u"
            },
            {
               "name":"WP_DB_USER",
               "value":"wordpress"
            }
         ]
      }
   ]
}
