{
   "entities":[
      {
         "name":"CentOS",
         "file":"CentOS.png"
      },
      {
         "name":"Jenkins",
         "file":"Jenkins.png"
      },
      {
         "name":"Redis",
         "file":"Redis.png"
      },
      {
         "name":"Windows.png",
         "file":"Windows"
      },
      {
         "name":"Wordpress",
         "file":"Wordpress.png"
      }
   ]
}
