{
   "name":"NTNXLAB",
   "domain":"ntnxlab.local",
   "directoryUrl":"ldap://172.31.0.201:389",
   "groupSearchType":"NON_RECURSIVE",
   "directoryType":"ACTIVE_DIRECTORY",
   "connectionType":"LDAP",
   "serviceAccountUsername":"administrator@ntnxlab.local",
   "serviceAccountPassword":"nutanix/4u"
}
