{
   "marketplace_apps":[
      {
         "app_name":"Kafka",
         "app_version":"3.0.0"
      },
      {
         "app_name":"Jenkins",
         "app_version":"4.0.0"
      },
      {
         "app_name":"MongoDB Sharding",
         "app_version":"4.0.0"
      },
      {
         "app_name":"Wordpress",
         "app_version":"1.0.0"
      }
   ]
}
