{
   "api_version":"3.1.0",
   "metadata":{
      "kind":"project"
   },
   "spec":{
      "name":"<project_name>",
      "resources":{
         "account_reference_list":[
            {
               "uuid":"<account_uuid>",
               "kind":"account",
               "name":"<account_name>"
            }
         ],
         "subnet_reference_list":[
            {
               "kind":"subnet",
               "name":"<subnet_name>",
               "uuid":"<subnet_uuid>"
            }
         ],
         "user_reference_list":[
            {
               "kind":"user",
               "name":"admin",
               "uuid":"00000000-0000-0000-0000-000000000000"
            }
         ],
         "environment_reference_list":[]
      }
   }
}
